name = "QuantumNLDiffEq"
uuid = "5411918f-e61c-4722-a33e-8517a813f4bd"
authors = ["SciML"]
version = "0.0.1"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ChainRulesCore = "1.15"
ForwardDiff = "0.10"
Optimisers = "0.2, 0.3, 0.4"
SciMLBase = "1, 2"
Yao = "0.8"
Zygote = "0.6, 0.7, 0.8"
julia = "1.6"

[extras]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test", "DifferentialEquations"]
